name: Lint Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: self-hosted  # The operating system for the runner

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify your Python version here
           steps:
      - name: Check Python Installed on EC2
        run: |
          python3.8 --version || echo "Python 3.8 is not installed"

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          check-latest: true  # Ensures it fetches the latest compatible version
          cache: 'pip'  # Optional: Enables caching for dependencies
          
      - name: Verify Python Version
        run: python --version  # Should now return Python 3.8

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8  # Install flake8 linter

      # Step 4: Run the linter
      - name: Run flake8
        run: flake8 .  # Lint the entire repository
